'use client'

import { ConnectModal, useCurrentAccount } from '@mysten/dapp-kit'
import { Button } from '@radix-ui/themes'

const CustomConnectButton = () => {
  const currentAccount = useCurrentAccount()

  return (
    <div className="px-4 py-10 bg-gradient-to-br from-pink-50 via-yellow-50 to-white rounded-2xl">
  <div className="flex flex-col items-center justify-center text-center max-w-2xl mx-auto">
    <h1 className="text-4xl sm:text-5xl font-extrabold text-pink-600 mb-4">
      🍰 Your Cake Icon
    </h1>

    <p className="text-lg sm:text-xl text-gray-800 mb-4 leading-relaxed">
      Discover your personality through flavor!  
      Answer 10 quick questions and let AI craft a <strong>one-of-a-kind cake icon</strong> just for you.
    </p>

    <p className="text-md sm:text-lg text-gray-700 mb-4 leading-relaxed">
      🎨 Both the <strong>image</strong> and the <strong>description</strong> are uniquely generated by AI — 
      based on your personality traits. No two results are alike!
    </p>

    <p className="text-md sm:text-lg text-gray-700 mb-6 leading-relaxed">
      💎 Mint your cake on-chain for just <strong>0.01 SUI</strong> and keep it forever as your delicious digital identity.
    </p>

    <p className="text-sm text-gray-500 italic mb-8">
      🎨 AI-generated • 🧠 Psychology-inspired • 💖 Yours forever
    </p>

    <ConnectModal
      trigger={
        <Button className="text-white text-lg bg-pink-500 hover:bg-pink-600 px-8 py-4 rounded-2xl shadow-lg transition duration-300">
          {currentAccount ? "Connected" : "Connect Wallet & Begin"}
        </Button>
      }
    />
  </div>
</div>
  )
}

export default CustomConnectButton
